@startuml 
sprite $FFICO032 [32x32/16] { 
BBBBBBBBBBBBBB39A93BBBBBBBBBBBBB
BBBBBBBBBBBBB39A5A93BBBBBBBBBBBB
BBBBBBBBBBBB39A525A93BBBBBBBBBBB
BBBBBBBBBBBB39A525A93BBBBBBBBBBB
BBBBBBBBBBBB39A525A93BBBBBBBBBBB
BBBBBBBBBBBB39A525A93BBBBBBBBBBB
BBBBBBBBBBBB39A525A93BBBBBBBBBBB
BBBBBBBBBBBB39A525A93BBBBBBBBBBB
BBBBBBBBBBBB39A525A93BBBBBBBBBBB
BBBBBBBBBBBB39A525A93BBBBBBBBBBB
BBBBBBBBBBBB39A525A93BBBBBBBBBBB
BBBBBBBBBBBB39A525A93BBBBBBBBBBB
BBBBBBBBBBBB39A525A93BBBBBBBBBBB
BBBBBBBBBBBB39A525A93BBBBBBBBBBB
BBBBBBBBBBBB39A525A93BBBBBBBBBBB
BBBBBBBBBBBB39A525A93BBBBBBBBBBB
BBBBBBBBBBBB39A565A93BBBBBBBBBBB
BBBBBBBBBBBB39A565A93BBBBBBBBBBB
BBBBBBBBBBBB39A565A93BBBBBBBBBBB
BBBBBBBBBB3339A565A9333BBBBBBBBB
BBBBBBBBB39939A565A93993BBBBBBBB
BBBBBBBB39AA9AA585AA9AA93BBBBBBB
BBBBBBB39A11A1184811A11A93BBBBBB
BBBBBBBB39AA1AA080AA1AA93BBBBBBB
BBBBBBBBB399A9A111A9A993BBBBBBBB
BBBBBBBBBB3399A010A9933BBBBBBBBB
BBBBBBBBBBBB39A090A93BBBBBBBBBBB
BBBBBBBBBBBB39A939A93BBBBBBBBBBB
BBBBBBBBBBBB39A090A93BBBBBBBBBBB
BBBBBBBBBBBB39A000A93BBBBBBBBBBB
BBBBBBBBBBBB39A777A93BBBBBBBBBBB
BBBBBBBBBBBBB39A7A93BBBBBBBBBBBB
} 
@enduml 
