INSERT INTO [TPLANCTOS] ([TIPOLANCTO], [DESC], [USER], [PROG], [DATA], [HORA]) VALUES ('IA', 'AJUSTE MANUAL DE ESTOQUE', 'SQL', 'SQL', date('now'), time('now'));
INSERT INTO [TPLANCTOS] ([TIPOLANCTO], [DESC], [USER], [PROG], [DATA], [HORA]) VALUES ('IT', 'TRANSFERENCIA DE ESTOQUE', 'SQL', 'SQL', date('now'), time('now'));
INSERT INTO [TPLANCTOS] ([TIPOLANCTO], [DESC], [USER], [PROG], [DATA], [HORA]) VALUES ('JA', 'LANCAMENTO CONTABIL AUTOMATICO', 'SQL', 'SQL', date('now'), time('now'));
INSERT INTO [TPLANCTOS] ([TIPOLANCTO], [DESC], [USER], [PROG], [DATA], [HORA]) VALUES ('JM', 'LANCAMENTO CONTABIL MANUAL', 'SQL', 'SQL', date('now'), time('now'));
