@startsalt
{
    {T
        + Structure         | Descrition
        + /                 | .
        ++ boot/            | .
        +++ bzImage         | (Kernel 2.2.18)
        +++ floppy.raw      | (Imagem de disco de boot DOS)
        +++ linux.bat       | (Arquivo de lote para chamada)
        +++ loadlin.exe     | (Programa de carga do Linux)
        +++ root.bin        | (Ambiente básico do Linux)
    }
}
@endsalt