@startuml
frame detect {
    agent "makeXfile" as a2
    file "/etc/X11/<driver name>" as a1
}
frame mount {
    file "/etc/X11/XF86Config.previous" as b1
    agent "driver name" as b2
    file "/etc/X11/XF86Config.next" as b3
}
file "/etc/X11/XF86Config" as c1
a1 -[dashed]-> a2
detect -----[bold]-> b2
b1 -[dashed]-> b2
b3 -[dashed]-> b2
mount --[bold]-> c1
@enduml